name: CI/CD pipeline

# Specify when the jobs run
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        
jobs:
    deploy:

        # Specifies the os to run the jobs on
        runs-on: ubuntu-22.04
        steps:
            # Specifies the github actions to use

            # This is the default github action
            - uses: actions/checkout@v2
            # This is the action to use to deploy to heroku
            - uses: akhileshns/heroku-deploy@v3.13.15
              with:
                # To deploy with heroku you need to specify these env variables in github
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}} # Must be unique in Heroku
                heroku_email: ${{secrets.HEROKU_EMAIL}}
                usedocker: true